# Generated by Django 3.2.7 on 2021-09-16 09:21

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='texts/', validators=[posts.validators.validate_file_extension])),
            ],
        ),
    ]
